### PR TITLE
Preact with Typescript implementation

### PR DESCRIPTION
**Pull request by krowter**
Issue [#38](https://github.com/teknologi-umum/decimal-clock/issues/38)

Please let me know if there are anything I can improve on.
Thank you

### CODE REVIEW

**Review by elianiva — APPROVED** [review]
anjay, ini mah bukan preact, tapi canvas implementation wkwkw

**Comment by herlangga72** [comment]
Ini mah #10. Sekalian aja pindahin ke pure html sama js. Gak usah pakai preact

**Comment by krowter** [comment]
Walah ngga liat ada issue sendiri utk html canvas. Sip2, tak pisahin dulu

**Review by herlangga72 — APPROVED** [review]
Seems good

**Review by ronnygunawan — APPROVED** [review]

**Pull request merged**
